# Generated by Django 5.1.7 on 2025-10-21 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="follows column-row-shelf format, for example 2-1-s1 means column 2, row 1, first shelf",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occupied", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("grape", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("vintage", models.PositiveIntegerField(default=2020)),
                (
                    "body",
                    models.CharField(
                        choices=[
                            ("light-body", "Light Body"),
                            ("medium-body", "Medium Body"),
                            ("full-body", "Full Body"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "tannin",
                    models.CharField(
                        choices=[
                            ("light-tannin", "Light Tannin"),
                            ("medium-tannin", "Medium Tannin"),
                            ("full-tannin", "Full Tannin"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "acidity",
                    models.CharField(
                        choices=[
                            ("low-acidity", "Low Acidity"),
                            ("medium-acidity", "Medium Acidity"),
                            ("high-acidity", "High Acidity"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "glass",
                    models.CharField(
                        choices=[
                            ("Standard", "Standard"),
                            ("Burgundy", "Burgundy"),
                            ("Bordeaux", "Bordeaux"),
                            ("Flute", "Flute"),
                        ],
                        max_length=15,
                    ),
                ),
                ("coravin", models.BooleanField(default=False)),
                ("sommNotes", models.TextField(blank=True)),
                ("imageUrl", models.URLField(blank=True)),
                (
                    "shelves",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Slots where this wine is stored.",
                        related_name="wines",
                        to="wineadmin.slot",
                    ),
                ),
            ],
        ),
    ]
