# Generated by Django 5.1.7 on 2025-10-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wineadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="glass",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Burgundy", "Burgundy"),
                    ("Bordeaux", "Bordeaux"),
                    ("Flute", "Flute"),
                    ("Tst", "Tasting glass"),
                ],
                max_length=15,
            ),
        ),
    ]
