# Generated by Django 5.1.7 on 2026-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0002_alter_wine_glass'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='btl_only',
            field=models.CharField(choices=[('Yes', 'Only by the Bottle'), ('No', 'available by the Glass/Carafe')], default='No', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wine',
            name='coravin',
            field=models.CharField(choices=[('Yes', 'Needs to be Coravined'), ('No', 'No Need to Coravin')], max_length=15),
        ),
    ]
