# Generated by Django 5.1.7 on 2026-03-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0003_wine_btl_only_alter_wine_coravin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='btl_only',
            field=models.CharField(choices=[('Yes', 'Only by the Bottle'), ('No', 'Available by the Glass/Carafe')], max_length=15),
        ),
    ]
