# Generated by Django 5.1.7 on 2026-03-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0004_alter_wine_btl_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
