# Generated by Django 5.1.7 on 2026-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0005_remove_wine_imageurl_wine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='image',
        ),
        migrations.AddField(
            model_name='wine',
            name='imageURL',
            field=models.URLField(blank=True),
        ),
    ]
