# Generated by Django 5.1.7 on 2026-03-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0006_remove_wine_image_wine_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='country',
            new_name='country_of_origin',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='name',
            new_name='wine_name',
        ),
    ]
