# Generated by Django 5.1.7 on 2026-03-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0007_rename_country_wine_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='sommNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
