# Generated by Django 5.1.7 on 2026-03-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0008_alter_wine_imageurl_alter_wine_sommnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.CharField(help_text='follows column-row-shelf format, for example c2-r1-s1 means column 2, row 1, first shelf', max_length=20, primary_key=True, serialize=False),
        ),
    ]
