# Generated by Django 5.1.7 on 2026-03-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0009_alter_slot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='occupied',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='shelves',
        ),
        migrations.AddField(
            model_name='slot',
            name='wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='wineadmin.wine'),
        ),
    ]
