# Generated by Django 5.1.7 on 2026-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0010_remove_slot_occupied_remove_wine_shelves_slot_wine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='btl_only',
            field=models.CharField(choices=[('Yes', 'Only by the Bottle'), ('No', 'Available by the Glass/Carafe/Bottle')], max_length=15),
        ),
        migrations.AlterField(
            model_name='wine',
            name='glass',
            field=models.CharField(choices=[('Standard', 'Standard Glass'), ('Burgundy', 'Burgundy Glass'), ('Bordeaux', 'Bordeaux Glass'), ('Flute', 'Flute Glass'), ('Tst', 'Tasting Glass')], max_length=15),
        ),
    ]
