# Generated by Django 5.1.7 on 2026-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0011_alter_wine_btl_only_alter_wine_glass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='tannin',
            field=models.CharField(choices=[('no-tannin', 'No/Very Low Tannin'), ('light-tannin', 'Light Tannin'), ('medium-tannin', 'Medium Tannin'), ('full-tannin', 'Full Tannin')], max_length=15),
        ),
    ]
