# Generated by Django 5.1.7 on 2026-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineadmin', '0012_alter_wine_tannin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='colour',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Rose', 'Rosé'), ('Orange', 'Orange (skin contact)')], default='Red', max_length=15),
            preserve_default=False,
        ),
    ]
